import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Nav } from "./ui/nav";
import ScrollbarContainer from "./components/scrollbar-container";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: LayoutProps<"/">) {
  const { children } = props;

  return (
    <html lang="en">
      <head>
        <link rel="javascript" href="/js/script.js" />
        <link rel="stylesheet" href="/font/font.css" />
        <noscript>
          <link rel="stylesheet" href="/font/font.css" />
        </noscript>
      </head>
      <body className={`antialiased w-screen h-screen overflow-clip`}>
        <SpeedInsights />
        <div className="grid grid-cols-[240px_1fr] h-full">
          <Nav />

          <ScrollbarContainer scroll={{ y: true }}>
            {children}
          </ScrollbarContainer>
        </div>
      </body>
    </html>
  );
}
