import type { Metadata } from "next";
import { headers } from "next/headers";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Nav } from "./ui/nav";
import ScrollbarContainer from "@/components/scrollbar-container";
import { deviceDetector } from "@/lib/utils";
import Provider from "@/provider";

import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: LayoutProps<"/">) {
  const header = await headers();
  const userAgent = header.get("user-agent");

  const device = deviceDetector.parse(userAgent ?? "");

  const { children } = props;

  return (
    <html lang="en">
      <head>
        <link rel="javascript" href="/js/script.js" />
        <link rel="stylesheet" href="/font/font.css" />
        <noscript>
          <link rel="stylesheet" href="/font/font.css" />
        </noscript>
      </head>
      <body className={`antialiased w-screen h-screen overflow-clip`}>
        <SpeedInsights />
        <Provider device={device}>
          <div className="grid grid-cols-[240px_1fr] h-full">
            <Nav />

            <ScrollbarContainer scroll={{ y: true }}>
              {children}
            </ScrollbarContainer>
          </div>
        </Provider>
      </body>
    </html>
  );
}
