import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/font/font.css" as="style" />
        <link rel="stylesheet" href="/font/font.css" />
        <noscript>
          <link rel="stylesheet" href="/font/font.css" />
        </noscript>
      </head>
      <body className={`antialiased w-screen h-screen`}>
        <SpeedInsights />
        {children}
      </body>
    </html>
  );
}
